name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: gcc -o appl *.c



  test:
      runs-on: ubuntu-letest
      
      steps:
      - uses: actions/checkout@v4
      - name: configure
        run: ./appl
