name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        set -e
        ./configure
    - name: make
      run: |
        set -e
        make
    - name: make check
      run: |
        set -e
        make check
    - name: make distcheck
      run: |
        set -e
        make distcheck
